// V46 PERFORMANCE ARCHITECTURE
var PERF_ROWS_CACHE_PREFIX_='PERF_ROWS_V1_';
var PERF_ROWS_CACHE_TTL_=240;
var PERF_ROWS_CHUNK_SIZE_=70000;
var PERF_DATE_HEADERS_={'Дата создания':1,'Дата обновления':1,'Дата публикации':1,'Дата готовности к работе':1,'Дата начала':1,'Дата обновления профиля':1,'Дата согласия':1,'Дата':1,'Дата открытия':1,'Последнее открытие':1};
function perfSearchVersion_(){try{return String(PropertiesService.getScriptProperties().getProperty('SEARCH_CACHE_VERSION')||'1');}catch(e){return '1';}}
function perfRowsCacheBase_(sheetName){return PERF_ROWS_CACHE_PREFIX_+perfSearchVersion_()+'_'+Utilities.base64EncodeWebSafe(String(sheetName||''));}
function perfRowsChunkKey_(base,i){return base+'_'+String(i);}
function perfDateValue_(v){if(v===null||v===undefined||v==='')return v;if(Object.prototype.toString.call(v)==='[object Date]')return v;if(typeof v==='number'&&isFinite(v)&&v>20000&&v<100000)return new Date(Math.round((v-25569)*86400000));return v;}
function perfRowsFromValues_(values){values=Array.isArray(values)?values:[];if(!values.length)return[];var h=(values[0]||[]).map(function(x){return String(x||'');}),out=[];for(var i=1;i<values.length;i++){var row=values[i]||[],o={};h.forEach(function(k,j){if(!k)return;var v=row[j];if(PERF_DATE_HEADERS_[k])v=perfDateValue_(v);o[k]=v===undefined?'':v;});out.push(o);}return out;}
function perfReadCachedRows_(sheetName){var base=perfRowsCacheBase_(sheetName),cache=CacheService.getScriptCache();try{var meta=cache.get(base+'_meta');if(!meta)return null;var m=JSON.parse(meta),keys=[];for(var i=0;i<Number(m.chunks||0);i++)keys.push(perfRowsChunkKey_(base,i));if(!keys.length)return[];var parts=cache.getAll(keys),raw='';for(var j=0;j<keys.length;j++){if(parts[keys[j]]===undefined)return null;raw+=parts[keys[j]];}var parsed=JSON.parse(raw);return Array.isArray(parsed)?parsed:null;}catch(e){return null;}}
function perfWriteCachedRows_(sheetName,rows){var base=perfRowsCacheBase_(sheetName),raw=JSON.stringify(rows||[]),cache=CacheService.getScriptCache();try{var oldMeta=cache.get(base+'_meta'),oldChunks=0;try{oldChunks=Number(JSON.parse(oldMeta||'{}').chunks||0);}catch(e){}var values={},chunks=0;for(var i=0;i<raw.length;i+=PERF_ROWS_CHUNK_SIZE_){values[perfRowsChunkKey_(base,chunks)]=raw.slice(i,i+PERF_ROWS_CHUNK_SIZE_);chunks++;}if(!chunks){values[perfRowsChunkKey_(base,0)]='[]';chunks=1;}values[base+'_meta']=JSON.stringify({chunks:chunks,updatedAt:Date.now()});cache.putAll(values,PERF_ROWS_CACHE_TTL_);if(oldChunks>chunks){var remove=[];for(var j=chunks;j<oldChunks;j++)remove.push(perfRowsChunkKey_(base,j));if(remove.length)cache.removeAll(remove);}}catch(e){try{cache.put(base+'_meta',JSON.stringify({chunks:0}),30);}catch(ignore){}}}
function perfReadRowsFallback_(sheetName){var sh=getSheet(sheetName);if(!sh||sh.getLastRow()<2)return[];var h=getHeaders(sh),v=sh.getDataRange().getValues(),out=[];for(var i=1;i<v.length;i++)out.push(rowObject(h,v[i]));return out;}
function perfReadRowsBatch_(sheetNames){var names=[];(sheetNames||[]).forEach(function(n){n=String(n||'').trim();if(n&&names.indexOf(n)<0)names.push(n);});if(!names.length)return{};var out={},missing=[];names.forEach(function(name){var hit=perfReadCachedRows_(name);if(hit!==null)out[name]=hit;else missing.push(name);});if(!missing.length)return out;try{if(typeof Sheets==='undefined'||!Sheets.Spreadsheets||!Sheets.Spreadsheets.Values)throw new Error('Sheets Advanced Service unavailable');var ranges=missing.map(function(name){return "'"+String(name).replace(/'/g,"''")+"'!A:ZZ";});var resp=Sheets.Spreadsheets.Values.batchGet(SPREADSHEET_ID,{ranges:ranges,majorDimension:'ROWS',valueRenderOption:'UNFORMATTED_VALUE'}),vr=resp&&resp.valueRanges||[];missing.forEach(function(name,idx){var rows=perfRowsFromValues_(vr[idx]&&vr[idx].values||[]);out[name]=rows;perfWriteCachedRows_(name,rows);});return out;}catch(apiErr){console.warn('V46 Sheets API batchGet fallback:',apiErr&&apiErr.message?apiErr.message:apiErr);missing.forEach(function(name){var rows=perfReadRowsFallback_(name);out[name]=rows;perfWriteCachedRows_(name,rows);});return out;}}
function perfReadRows_(sheetName){return perfReadRowsBatch_([sheetName])[String(sheetName||'')]||[];}
